main:
    qcow_image: ./data/ubuntu.qcow2 # location of the qcow image
    block_dev: sda1 # block device
    bridge: br0 # bridge name
    vm_username: root # username of the VM
    vm_password: hello # password of the VM
    log_level: INFO # log level DEBUG, INFO, ERROR
test_vm_config:
    num_of_vm: 2 # number of VM to be launched
    cpu: 4 # number of cpu of each VM in step 2
    ram: 8192 # RAM size in MB of each VM, in step 2
